#!/bin/bash -xe

export MINIKUBE_IP=$(minikube ip)

cd $(dirname $0)

openssl req -new -x509 -nodes -keyout server.key -days 3650 \
  -subj "/CN=demoapp-puma.${MINIKUBE_IP}.nip.io" \
  -extensions v3_req \
  -config <(cat openssl.conf | envsubst '$MINIKUBE_IP') > server.pem
kubectl create secret tls demoapp-puma-tls --key server.key --cert server.pem
