#!/bin/bash -xe

export COMMON_NAME=$1

cd $(dirname $0)
openssl req -new -x509 -nodes -keyout server.key -days 3650 \
  -subj "/CN=${COMMON_NAME}" \
  -extensions v3_req \
  -config <(cat openssl.conf | envsubst '$COMMON_NAME') > server.pem
openssl x509 -text < server.pem
